# Generated by Django 5.0 on 2023-12-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(default='images/imagen_default.jpg', upload_to='images/', verbose_name='Image')),
                ('github', models.URLField(blank=True, verbose_name='Github')),
                ('live', models.URLField(blank=True, verbose_name='Live')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
            },
        ),
    ]
